# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DAO Education
email: hello@dao.education
description: >- # this means to ignore newlines until "baseurl:"
  Capacitación para un mundo digital y descentralizado, a través 
  de la programación y conocimientos que te permitan diseñar tu prototipo de
  una DAO
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://daoe_staging.constata.eu" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/logo.png"

staging_api_url: "https://api_daoe_staging.constata.eu"
prod_api_url: "https://api_daoe.constata.eu"
dev_api_url: "http://127.0.0.1:8000"

collections:
  profesores:
    output: true
    permalink: /profesores/:path/
  programas:
    output: true
    permalink: /programas/:path/
  noticias:
    output: true
    permalink: /noticias/:path/
  eventos:
    output: true
    permalink: /eventos/:path/

# Social Media
instagram: daoeducation
twitter_user: educationDAO
#github_username: daoeducation
#facebook:
#linkedin:

defaults:
  -
    values:
      image: /assets/images/logo@3x.png #default OG image for all pages
      twitter:
        card: "summary"

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - spec
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
#theme: jekyll-theme-minimal
