defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.6.5-buster-browsers-legacy
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: RSpec
          command: |
            bundle exec rspec --profile 10 \
                              --format progress
        


workflows:
  version: 2
  integration:
    jobs:
      - build
