[global]
secret_key="DEADBEEF12345678DEADBEEF12345678DEADBEEF12345678DEADBEEF12345678"
stripe_price_id="price_1I18owDVE5TJAnJjdiK3yzBz"
stripe_public_key="pk_test_51I18k3DVE5TJAnJjBNIvxFCc6sOb24dSwTe7IqZ1ted5xJL27n27DuOe6OSaQVF7poJ2jtdOw0TbB2kM9w8THQWP005fYn1HsV"
stripe_secret_key="sk_test_51I18k3DVE5TJAnJj5gAroicklr21G7lo9yuxxGmTXFXjpaJq3NhqUUqfj9mwPITgbMwDYiFiH7ZTeMbqPWXGcpmH00VlNvR78O"
checkout_domain="http://localhost:4000"
recaptcha_site_key="6LcxPiAaAAAAAGoL4FuzYFIE6l7JpfUgnv1chmXm"
recaptcha_private_key="6LcxPiAaAAAAADMIz4QWIxcU9fJl1esLhzJxxP4d"
