[global]
secret_key="0b1817d28502ed35dd6566241a314fd85768fd70129478fe3db666a7449962e9"
stripe_price_id="price_1I8QQvDVE5TJAnJjeu8lJtHQ"
stripe_public_key="pk_test_51I18k3DVE5TJAnJjBNIvxFCc6sOb24dSwTe7IqZ1ted5xJL27n27DuOe6OSaQVF7poJ2jtdOw0TbB2kM9w8THQWP005fYn1HsV"
stripe_secret_key="sk_test_51I18k3DVE5TJAnJj5gAroicklr21G7lo9yuxxGmTXFXjpaJq3NhqUUqfj9mwPITgbMwDYiFiH7ZTeMbqPWXGcpmH00VlNvR78O"
checkout_domain="http://localhost:4000"
recaptcha_site_key="6LeQdigaAAAAAHaAAhZ-x_oYeLRXYaYQZlb9MQ94"
recaptcha_private_key="6LeQdigaAAAAAIxImj-L41t4UaHgyCTZHqMNkm0o"
